on:
  watch:
    types: started
  workflow_dispatch:
jobs:
  AutoSyncProcess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Gclone Install
      run: wget -qO- https://git.io/gclone.sh | sudo bash
    - name: Aria2 Install
      run: sudo apt install -y aria2
    - name: Rclone Synchronizing file
      run: |
        sudo apt-get update && sudo apt-get install software-properties-common -y && sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable && sudo apt-get update && sudo apt-get install qbittorrent-nox -y && sudo qbittorrent-nox -d --webui-port=4444 && sudo snap install ngrok && sudo ngrok authtoken 1lxRC0XzWVv0L8ccHLdEXVdP5kn_4vSTF9AM2r2Kbv8YMwro9 && sudo ngrok http 4444
