name: Transfers
on:
  watch:
    types: started
  workflow_dispatch:
jobs:
  AutoSyncProcess:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Rclone Install
      run: |
        wget -q https://github.com/jonntd/gclone/releases/download/v1.52.13/gclone_1.52.13_Linux_x86_64.gz
        gunzip gclone_1.52.13_Linux_x86_64.gz
        sudo mv gclone_1.52.13_Linux_x86_64 /usr/bin/gclone
        chmod +x /usr/bin/gclone
        sudo apt install unrar -y -q
        sudo apt install -y aria2
    - name: Inject Rclone config
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      run: |
        wget -q https://github.com/ukiyo99/majgaijgojjwoijoga/raw/main/accounts.rar
        unrar -p'${{ secrets.RAR_PSWD }}' e accounts.rar ~/accounts/
        index=`ls -l ~/accounts |grep "^-"|wc -l`
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${RCLONE_CONF/1.json/$((RANDOM%$index+1)).json}
        EOF
        mkdir -p ~/.aria2/
        cat >  ~/.aria2/aria2.conf  << EOF
        ${{ secrets.ARIA2_CONF }}
        EOF
    - name: Aria2_Downloading_File
      run: |
        ${{ secrets.OTENKIYA_DL }}
    - name: Rclone Synchronizing file
      run: |
        gclone copy downloads gc2:{0ACd8s2TQA74_Uk9PVA}/01 -v --cache-chunk-total-size 20G --transfers=12 --drive-chunk-size 128M
