name: AutoDownloader
on:
  gollum
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: gclone Install
      run: curl wget -qO- https://git.io/gclone.sh | sudo bash
    - name: Aria2 Install
      run: sudo apt install -y aria2
    - name: Inject Rclone&Aria2 config
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.RCLONE_CONF }}
        EOF
        mkdir -p ~/.aria2/
        cat >  ~/.aria2/aria2.conf  << EOF
        ${{ secrets.ARIA2_CONF }}
        EOF
        mkdir -p /home/runner/accounts/ 
        cat >  /home/runner/accounts/81.json  << EOF
        ${{ secrets.SA81_CONF }}
        EOF
        cat >  /home/runner/accounts/82.json  << EOF
        ${{ secrets.SA82_CONF }}
        EOF
        cat >  /home/runner/accounts/83.json  << EOF
        ${{ secrets.SA83_CONF }}
        EOF
        cat >  /home/runner/accounts/84.json  << EOF
        ${{ secrets.SA84_CONF }}
        EOF
        cat >  /home/runner/accounts/85.json  << EOF
        ${{ secrets.SA85_CONF }}
        EOF
    - name: Aria2_Downloading_File
      run: |
        git clone "https://github.com/${GITHUB_REPOSITORY}.wiki.git"
        wiki=`echo $GITHUB_REPOSITORY | cut -d "/" -f 2`.wiki
        cd $wiki
        mdfile=`git log --pretty=format: -1 --name-only *.md`
        cd ..
        aria2c --seed-time=0 -d downloads `cat $wiki/$mdfile | xargs`
        echo "${mdfile:0:-3}:" > DEST
    - name: Rclone Synchronizing file
      run: |
        gclone copy downloads gc2:{1kqZdIfbFiigDdnzc-i5Pb67r0QBXE1al} -v --cache-chunk-total-size 20G --transfers=15 --drive-chunk-size 128M
